name: talentVerse CI

on: # 언제 실행될지 정의
  workflow_dispatch: # 수동 실행
  push: # PUSH 됐을 때
    branches: [main] # main 브랜치
  pull_request: # PR
    types: [opened, reopened, synchronize] # PR 이벤트에 반응
    branches: [main] # main 브랜치

env: # 워크플로우에서 사용할 환경 변수 설정
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com # ECR 레지스트리 주소 설정
  ECR_REPOSITORY: talentverse # ECR 리포지토리 이름 설정
  IMAGE_TAG: latest # 이미지 태그를 'latest'로 설정

jobs:
  build-and-push: # CI 작업의 이름 정의
    runs-on: ubuntu-24.04 # 작업이 실행될 환경(OS)을 Ubuntu 24.04로 지정

    steps: # 작업 내에서 실행될 단계(step)들을 정의
      - name: Checkout source code # 소스 코드를 체크아웃하는 단계
        uses: actions/checkout@v4 # GitHub 리포지토리의 소스 코드를 가져오기 위해 actions/checkout 액션 사용

      - name: Set environment variables  # 환경 변수를 설정하는 단계
        run: echo "${{ secrets.ENV }}" > .env  # GitHub Secrets에 저장된 ENV 값을 .env 파일로 생성

      - name: Set up Docker Buildx # Docker Buildx를 설정하는 단계
        uses: docker/setup-buildx-action@v2 # Docker의 Buildx 기능을 사용하여 빌드 환경을 설정
        
      - name: Configure AWS credentials # AWS 자격 증명을 설정하는 단계
        uses: aws-actions/configure-aws-credentials@v2 # AWS CLI를 사용하기 위해 자격 증명 설정
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS Access Key ID를 GitHub Secrets에서 가져옴
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS Secret Access Key를 GitHub Secrets에서 가져옴
          aws-region: ${{ secrets.AWS_REGION }} # AWS 리전을 GitHub Secrets에서 가져와 설정
      
      - name: Log in to Amazon ECR  # Amazon ECR에 로그인하는 단계
        run: aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        # AWS CLI를 사용하여 ECR에 로그인하고 Docker 자격 증명을 설정합니다.
  
      - name: Build and Push Docker image to ECR # Docker 이미지를 빌드하고 ECR에 푸시하는 단계
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .  # Docker 이미지를 빌드하고 태그 설정
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG  # 빌드된 이미지를 ECR에 푸시
